# Generated by Django 5.0 on 2024-10-17 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0005_alter_product_barcode_alter_product_buying_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="buying_price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="product",
            name="selling_price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
