# Generated by Django 5.0 on 2024-10-17 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0008_product_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="description",
        ),
    ]
